### PR TITLE
fix(client): pass user details and add loader for profile

### LINKED ISSUE #153: No loader in my profile and public profile page

### PR DESCRIPTION
**Pull request by piyushagwl007**
## PR Checklist
Please check that your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/pesto-students/batch-9-Lumen/wiki/Commit-message-convention)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] GIFs/Videos/Images added (only for frontend changes)

## PR Type
What kind of change does this PR introduce? 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Infrastructure changes
- [ ] Other... Please describe:
Issue Number: 
fixes #153 

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by piyushagwl007** [comment]
Profile and blogs loader
eee

File: client/src/containers/Profile/ProfileBlogsPublic.jsx [hunk 1]
```diff
@@ -2,24 +2,30 @@ import React, { useState } from 'react';
...
+  const [blogs = [], ,  fetched] = useGetUserBlogs(publicUser);
+  const loaderStyles = {
+    flexDirection :'column'
+  }
   return (
     <div>
       <h1 className={styles.title}> Blogs </h1>
-      {blogsCards}
+      {
+        !fetched ? <BlogsLoader externalStyles={loaderStyles}/> :
```
Comment (nihalanisumit) [inline client/src/containers/Profile/ProfileBlogsPublic.jsx:26]: LOL, nice re-use xD

**Review by nihalanisumit — APPROVED** [review]
LGTM
